version: '3'
services:
  front:
    build:
      context: .
      dockerfile: ./docker/front/Dockerfile
    container_name: react-container
    tty: true
    volumes:
      - ./front:/app/front
    command: sh -c "cd /app/front && npm install && npm start"
    ports:
      - 3000:3000
  
  server:
    build: 
      context: .
      dockerfile: ./docker/server/Dockerfile
    container_name: go-container
    env_file:
      - docker-compose.env
    ports:
      - 8080:8080
    tty: true
    volumes:
      - ./server:/app/server
    command: sh -c "cd /app/server && go run *.go"